### ISSUE TITLE
Execute

### ISSUE THREAD

**Issue by elioenaielt** [dheera/ros-imu-bno055#1]
Hello dheera.
Amazing your work will be much easier because you don't have to use RTIMUlib but I don't know how to run it, would it be with an ide or Qt creator? (I use jetson TX2)
Thank you very much in advance.

**Comment by dheera** [comment]
Hi @elioenaielt this is a ROS node. You would launch it by adding it to your catkin_ws directory or wherever your catkin workspace is, putting something like this in a imu.launch file:
```
<launch>
    <node ns="imu" name="bno055_i2c_node" pkg="imu_bno055" type="bno055_i2c_node" respawn="true" respawn_delay="2">
        <param name="device" type="string" value="/dev/i2c-1"/>
    </node>
</launch>
```
And then running
```
$ roslaunch imu.launch
```
