### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by seoho-kang** [dheera/ros-imu-bno055#2]
Hi, how did you wire bno055 to tx2?

vin -> 5v
gnd -> gnd
sda -> sda(A4)
scl -> scl(A5)

Do I just wire like above between tx2 and bno055 directly?

**Comment by dheera** [comment]
Yes, that should work, for GND, SCL, SDA.

For VIN, beware that the BNO055 wants a supply voltage of 2.4V-3.6V, as per page 12 of the datasheet. However, many BNO055 boards, including e.g. the Adafruit BNO055 breakout, include a regulator that allows you to supply 5V, so read the documentation of your particular breakout board.
